# Generated by Django 5.0.7 on 2024-08-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_test"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test",
                to="materials.lesson",
                verbose_name="Курс",
            ),
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Укажите ваш ответ", verbose_name="Попытка ответа"
                    ),
                ),
                (
                    "answer_bool",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Правильно/Неправильно"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        help_text="Укажите тест",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_answer",
                        to="materials.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка ответа",
                "verbose_name_plural": "Попытки ответа",
            },
        ),
    ]
